### ISSUE TITLE
todo: Sicherheitskonzept

### ISSUE THREAD

**Issue by NoobTracker** [BixConcept/tutoring-backend-express#9]
Puh, ich weiß gar nicht, wo ich das reinpacken soll, das Frontend versucht, Backend zu sein :)
Also, Leude, wenn ihr nicht wollt, dass ich mich ohne Schuladresse registrieren kann, dann prüft ihr das *bitte serverseitig*. Mit meinem Dutzend Hirnzellchen habe ich es geschafft, die Dev Tools rauszukramen und das `disable` auf dem Registrierungsbutton zu löschen. Dafür muss man nicht studiert haben. Generell nimmt der Server sehr freudig *alles* entgegen, das ist vielleicht auch nicht so cool. Fixt das einfach mal, damit wenigstens wir Script Kiddies dran abprallen :P
Wenigstens könnte HTML injecten leichter sein, es kommt auch mit `">` in einer Mailadresse klar, wobei ich gar nicht weiß, wie lustig es ist, wenn beliebiger Text in ein `mailto:` gepackt werden kann (vermutlich harmlos?). Oh, oder ans Ende eines Signallinks. Naja. Ich bin schon leicht beeindruckt, dass ich `NaN`klässlern keine Nachhilfe geben kann :D

**Comment by 3nt3** [comment]
The email validation stuff exists in theory (although I'm not terribly happy with the way I implemented it in a hurry when some guy messaged me on signal in the middle of the night telling me there's a _minor_ security vuln in the code) -- now about the other stuff.

About the HTML injection: I basically hoped, React would deal with it lol.

Putting user input inside the `href` of a link (even after `mailto:`) pretty open to XSS probably though and that should probably be guarded more.

`NaN` being a valid value for the `number` type in typescript is of course not really practical in terms of a tutors high school year but it's not really critical since that value can't be set from the frontend (hopefully?) and doesn't have any effect per se except looking weird.

**Comment by NoobTracker** [comment]
Okay, didn't know that I should've written that in English - I just saw that the project description is in German so I assumed that's the preferred language. Through a brief search I was only able to find ways of creating malicious mailto:s that rely on mail clients doing dumb things, XSS is probably not an issue there, `"` and `>` are escaped. And I just wanted to compliment something about the otherwise dubious input validation, that's why I mentioned the grade check ;)
Oh, and `SELECT id, name FROM subject WHERE id IN (${givenIds.join(",")});` looks ... like an accident that's about to happen :D

**Comment by durek1337** [comment]
Ich habe nichts gegen Deutsch. Geht mir schneller von der Hand. Ich denke auch, dass es hier nicht nötig ist, da das Projekt nach aktuellem Stand auch keine multilingualen Ambitionen hegt. Mit den Links über mailto kann man ja noch leben (auch wenn das nicht schön ist - eigentlich sind die Accounts ja personalisiert... und man kann jemanden notfalls dafür rügen). Dass so sicherheitsrelevante Überprüfungen des Backends (nur) in den Client gegeben werden, darf wirklich nicht sein. Dabei spielt das Framework keine Rolle. Es ist immer ein Sicherheitsrisiko. Das muss schleunigst behoben werden. Solange die clientseitige Überprüfung nicht im Backend stattfindet, empfehle ich den Verantwortlichen die Abschaltung. Letzteres mit dem join ist mal wieder ein Skalierungsproblem und beeinträchtigt die Stabilität. Es ist leider eines von mehreren Skalierungsproblemen, die mir aufgefallen sind.


Danke, dass du nach deiner Überprüfung Bescheid gibst, NoobTracker!

**Comment by 3nt3** [comment]
Wie bereits geschrieben, ist das keine reine client side überprüfung lol

**Comment by NoobTracker** [comment]
Die serverseitige Validierung war aber effektiv auch nur ein
```
  if (false)
    return res.status(400).json({ msg: "invalid email" });
```
Trotz des eigentlich sinnvollen Konzeptes zählt das nur so halb :P
Ich habe mir die regex mal einen Moment lang angeguckt, und mir ist keine sinnvolle Adresse eingefallen, die nicht als valide gilt. Solange in der gesamten Adresse irgendwo ein Punkt ist, im Zweifelsfall das `.com` in `john@doe.com`, matcht das. 
~~ach, und ich bin mal gespannt, wann euch der goto fail passiert~~

**Comment by durek1337** [comment]
> Wie bereits geschrieben, ist das keine reine client side überprüfung lol


```
const checkEmailValidity = (email: string): boolean => {
  return /(.*)\.(.*)@gymhaan.de/.test(email);
};
```
...
```
const emailSplitByAt = email.split('@');
  const removedAllButFirstAt = emailSplitByAt[0] + '@' + emailSplitByAt.slice(1, emailSplitByAt.length).join('');

// hackery because frontend
  if (!checkEmailValidity(removedAllButFirstAt) && !checkEmailValidity(removedAllButFirstAt + "@gymhaan.de"))
    return res.status(400).json({ msg: "invalid email" });
```

das klappt so aber trotzdem nicht. Oder um es mit deinen Worten zu schreiben: lol

edit: hier mal ein JavaScript-Beispiel für die Konsole im Browser.

```
const email = "ich bin gar keine E-Mail-Adresse.com";
const checkEmailValidity = (email) => {
  return /(.*)\.(.*)@gymhaan.de/.test(email);
};

const emailSplitByAt = email.split('@');
  const removedAllButFirstAt = emailSplitByAt[0] + '@' + emailSplitByAt.slice(1, emailSplitByAt.length).join('');

// hackery because frontend
  if (!checkEmailValidity(removedAllButFirstAt) && !checkEmailValidity(removedAllButFirstAt + "@gymhaan.de"))
    console.log("invalid");
else console.log("valid");
```

**Comment by NoobTracker** [comment]
Also wir haben jetzt viel Text geschrieben, aber wie wär's langsam mal mit nem Fix? :)
Zum Verständnis: Wenn eine Mailadresse ohne das `@gymhaan.de` angegeben wird, wird dann eigentlich eine kaputte Mailadresse in die Datenbank geschrieben? Der Mail wird ja nur temporär das `@gymhaan.de` zur Validierung angefügt, soweit ich das gesehen habe. 
Ich schlage vor, ihr nehmt einfach alles vor dem ersten `@` (potentiell alles, was eingetragen wurde) und fügt dann `@gymhaan.de` an, fertig. Hab die RFCs nicht gewälzt, aber das dürfte schon mal weniger schlimm sein. Und da der Client schon überprüft, ob da ein `@gymhaan.de` ist, müsst ihr da theoretisch nicht mal eine Fehlermeldung zurückgeben, wenn die Adresse auf was anderes endet, das passiert nur, wenn da wer die Dev Tools rausholt.

**Comment by 3nt3** [comment]
@NoobTracker theoretisch ist das alles kein ding, denk ich, mir fehlt nur irgendwie die motivation wenn die bislang einzige instanz eh von niemandem wirklich geupdatet werden kann.

und @durek1337 ich finde deinen tonfall teilweise ein bisschen anmaßend dafür dass ich das hier eigentlich alles alleine in meiner freizeit gemacht habe und mir eigentlich von der schule hauptsächlich kommuniziert wurde, dass das ja gar nicht meine aufgabe gewesen sei und was ich denn überhaupt wolle.

**Comment by 3nt3** [comment]
aber falls irgendwer nen PR hat, kann ich mir den gerne ankucken

**Comment by NoobTracker** [comment]
> mir fehlt nur irgendwie die motivation wenn die bislang einzige instanz eh von niemandem wirklich geupdatet werden kann.

Moment, ihr habt irgendwo einen Server stehen und niemand kann dran, um neue Versionen aufzuspielen? Wie kriegt man das überhaupt hin? ^^

**Comment by 3nt3** [comment]
früher hat das @durek1337 gemachr, der ist jetzt nicht mehr an der schule

**Comment by durek1337** [comment]
> und @durek1337 ich finde deinen tonfall teilweise ein bisschen anmaßend dafür dass ich das hier eigentlich alles alleine in meiner freizeit gemacht habe und mir eigentlich von der schule hauptsächlich kommuniziert wurde, dass das ja gar nicht meine aufgabe gewesen sei und was ich denn überhaupt wolle.

Verstehe ich. Es war allerdings auch meine Freizeit und Du redest mit anderen auch so. Ich schätze sehr, was du in deiner Freizeit getan hast, aber ich hätte mir dennoch hin und wieder etwas mehr Demut von dir gewünscht. Ich bitte um Entschuldigung für meinen Tonfall und bedanke mich, dass du dich der Sache angenommen hast.

>  früher hat das @durek1337 gemachr, der ist jetzt nicht mehr an der schule

Ich kann das trotzdem noch machen.
